package proxy

import (
	"bufio"
	"context"
	"crypto/tls"
	"encoding/base64"
	"fmt"
	"math/rand/v2"
	"net"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/codex2api/security"
	utls "github.com/refraction-networking/utls"
	"golang.org/x/net/http2"
	xproxy "golang.org/x/net/proxy"
)

// CodexTLSImpersonationEnabled only selects the opt-in rustls ClientHello profile.
// It does not claim byte-for-byte equivalence to every Codex/platform build.
func CodexTLSImpersonationEnabled() bool { return codexEnvEnabled("CODEX_TLS_IMPERSONATE") }

// codexRustlsHello matches the initial rustls/aws-lc hello captured locally from
// official codex-cli 0.154.0 with CODEX_CA_CERTIFICATE selecting rustls. Native
// platform TLS can differ. Fresh key shares/randoms are generated by uTLS; no
// captured secrets or certificate-verification bypass are used.
func codexRustlsHello(alpn []string) *utls.ClientHelloSpec {
	extensions := []utls.TLSExtension{
		&utls.SNIExtension{},
		&utls.StatusRequestExtension{},
		&utls.SupportedCurvesExtension{Curves: []utls.CurveID{utls.X25519MLKEM768, utls.X25519, utls.CurveP256, utls.CurveP384}},
		&utls.SupportedPointsExtension{SupportedPoints: []byte{0}},
		&utls.SignatureAlgorithmsExtension{SupportedSignatureAlgorithms: []utls.SignatureScheme{
			0x0503, 0x0403, 0x0603, 0x0807, 0x0806, 0x0805, 0x0804, 0x0601, 0x0501, 0x0401,
		}},
		&utls.ExtendedMasterSecretExtension{},
		&utls.SessionTicketExtension{},
		&utls.SupportedVersionsExtension{Versions: []uint16{utls.VersionTLS13, utls.VersionTLS12}},
		&utls.PSKKeyExchangeModesExtension{Modes: []uint8{utls.PskModeDHE}},
		&utls.KeyShareExtension{KeyShares: []utls.KeyShare{{Group: utls.X25519MLKEM768}, {Group: utls.X25519}}},
	}
	if len(alpn) != 0 {
		extensions = append(extensions, &utls.ALPNExtension{AlpnProtocols: alpn})
	}
	// rustls permutes extension order; freezing a single captured order would
	// itself add a persistent fingerprint.
	rand.Shuffle(len(extensions), func(i, j int) { extensions[i], extensions[j] = extensions[j], extensions[i] })
	return &utls.ClientHelloSpec{
		TLSVersMin: utls.VersionTLS12, TLSVersMax: utls.VersionTLS13,
		CipherSuites:       []uint16{0x1302, 0x1301, 0x1303, 0xc02c, 0xc02b, 0xcca9, 0xc030, 0xc02f, 0xcca8, 0x00ff},
		CompressionMethods: []byte{0}, Extensions: extensions,
	}
}

// DialCodexTLS is shared by native HTTP/2 and WebSocket. WS uses no ALPN,
// since Gorilla performs the HTTP/1.1 upgrade itself. Proxy errors fail closed.
func DialCodexTLS(ctx context.Context, network, address, proxyURL string, alpn []string) (net.Conn, error) {
	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()
	conn, err := dialCodexProfileTunnel(ctx, network, address, proxyURL)
	if err != nil {
		return nil, err
	}
	host, _, err := net.SplitHostPort(address)
	if err != nil {
		conn.Close()
		return nil, err
	}
	tlsConn := utls.UClient(conn, &utls.Config{ServerName: host, MinVersion: utls.VersionTLS12}, utls.HelloCustom)
	if err = tlsConn.ApplyPreset(codexRustlsHello(alpn)); err == nil {
		err = tlsConn.HandshakeContext(ctx)
	}
	if err != nil {
		conn.Close()
		return nil, fmt.Errorf("Codex TLS profile handshake: %w", err)
	}
	if len(alpn) > 0 && tlsConn.ConnectionState().NegotiatedProtocol != "h2" {
		conn.Close()
		return nil, fmt.Errorf("Codex TLS profile: upstream did not negotiate h2")
	}
	return tlsConn, nil
}

func newCodexProfileTransport(proxyURL string) http.RoundTripper {
	return &http2.Transport{
		DialTLSContext: func(ctx context.Context, network, addr string, _ *tls.Config) (net.Conn, error) {
			return DialCodexTLS(ctx, network, addr, proxyURL, []string{"h2", "http/1.1"})
		},
		ReadIdleTimeout: codexHTTP2ReadIdleTimeout, PingTimeout: codexHTTP2PingTimeout,
		IdleConnTimeout: codexUTLSIdleConnTimeout,
	}
}

func dialCodexProfileTunnel(ctx context.Context, network, address, rawProxy string) (net.Conn, error) {
	dialer := &net.Dialer{Timeout: 10 * time.Second, KeepAlive: 30 * time.Second}
	if strings.TrimSpace(rawProxy) == "" {
		// Match the standard transport's environment proxy selection.
		u, err := http.ProxyFromEnvironment(&http.Request{URL: &url.URL{Scheme: "https", Host: address}})
		if err != nil {
			return nil, err
		}
		if u == nil {
			return dialer.DialContext(ctx, network, address)
		}
		rawProxy = u.String()
	}
	u, err := security.ParseProxyURL(rawProxy)
	if err != nil {
		return nil, fmt.Errorf("Codex TLS profile: invalid proxy configuration")
	}
	if u.Scheme == "socks5" || u.Scheme == "socks5h" {
		var credentials *xproxy.Auth
		if u.User != nil {
			password, _ := u.User.Password()
			credentials = &xproxy.Auth{User: u.User.Username(), Password: password}
		}
		socks, err := xproxy.SOCKS5("tcp", u.Host, credentials, dialer)
		if err != nil {
			return nil, err
		}
		return socks.(xproxy.ContextDialer).DialContext(ctx, network, address)
	}
	if u.Scheme != "http" && u.Scheme != "https" {
		return nil, fmt.Errorf("Codex TLS profile: unsupported proxy scheme")
	}
	port := u.Port()
	if port == "" {
		port = "80"
		if u.Scheme == "https" {
			port = "443"
		}
	}
	conn, err := dialer.DialContext(ctx, "tcp", net.JoinHostPort(u.Hostname(), port))
	if err != nil {
		return nil, err
	}
	success := false
	defer func() {
		if !success {
			conn.Close()
		}
	}()
	stop := context.AfterFunc(ctx, func() { conn.Close() })
	defer stop()
	if deadline, ok := ctx.Deadline(); ok {
		_ = conn.SetDeadline(deadline)
	}
	if u.Scheme == "https" {
		outer := tls.Client(conn, &tls.Config{ServerName: u.Hostname(), MinVersion: tls.VersionTLS12})
		if err := outer.HandshakeContext(ctx); err != nil {
			return nil, err
		}
		conn = outer
	}
	req := &http.Request{Method: http.MethodConnect, URL: &url.URL{Opaque: address}, Host: address, Header: make(http.Header)}
	if u.User != nil {
		password, _ := u.User.Password()
		req.Header.Set("Proxy-Authorization", "Basic "+base64.StdEncoding.EncodeToString([]byte(u.User.Username()+":"+password)))
	}
	if err := req.Write(conn); err != nil {
		return nil, err
	}
	reader := bufio.NewReader(conn)
	resp, err := http.ReadResponse(reader, req)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("Codex TLS proxy CONNECT status %d", resp.StatusCode)
	}
	if !stop() && ctx.Err() != nil {
		return nil, ctx.Err()
	}
	_ = conn.SetDeadline(time.Time{})
	success = true
	return &bufferedConn{Conn: conn, reader: reader}, nil
}
